"""Add notifications

Revision ID: 1bb92a50102d
Revises: de6f28ab62e1
Create Date: 2020-11-22 09:24:32.317333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb92a50102d'
down_revision = 'de6f28ab62e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_email', sa.String(length=80), nullable=True),
    sa.Column('lost_dog_id', sa.Integer(), nullable=True),
    sa.Column('reported_dog_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
