"""empty message

Revision ID: aaa46195642b
Revises: 
Create Date: 2020-11-21 11:40:38.083920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa46195642b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_dog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_email', sa.String(length=80), nullable=True),
    sa.Column('found', sa.Boolean(), nullable=True),
    sa.Column('coat_colour', sa.Enum('brown', 'red', 'gold', 'cream', 'black', 'grey', 'white', 'other', name='coatcolour'), nullable=True),
    sa.Column('breed', sa.String(length=80), nullable=True),
    sa.Column('picture', sa.LargeBinary(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reported_dog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coat_colour', sa.Enum('brown', 'red', 'gold', 'cream', 'black', 'grey', 'white', 'other', name='coatcolour'), nullable=True),
    sa.Column('breed', sa.String(length=80), nullable=True),
    sa.Column('picture', sa.LargeBinary(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reported_dog')
    op.drop_table('lost_dog')
    # ### end Alembic commands ###
