"""Add description

Revision ID: de6f28ab62e1
Revises: 0cc609713c41
Create Date: 2020-11-22 08:50:05.400521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6f28ab62e1'
down_revision = '0cc609713c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost_dog', sa.Column('details', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lost_dog', 'details')
    # ### end Alembic commands ###
